version: "3.7"

networks:
    internal-net:
        name: internal-net
        driver: bridge
    nginx-reverse-proxy-manager-network:
        name: nginx-reverse-proxy-manager-network
        external: true
        driver: bridge

services:
    geneweb:
        image: callumgare/geneweb:latest
        container_name: geneweb
        hostname: geneweb
        networks:
            - internal-net
            - nginx-reverse-proxy-manager-network
        volumes:
            - ./geneweb-data:/geneweb/bases
            - ./exchange:/exchange
            - type: bind
              source: ./config/only.txt
              target: /geneweb/gw/only.txt
            - type: bind
              source: ./config/gwd.xcl
              target: /geneweb/gw/gwd.xcl
            - type: bind
              source: ./scripts/start_setup.sh
              target: /geneweb/start_setup.sh
            - type: bind
              source: ./scripts/start_setup_daemon.sh
              target: /geneweb/start_setup_daemon.sh
        working_dir: /geneweb
        ports:
            - 2316:2316
            - 2317:2317
        restart: always
